### PR TITLE
minification to package.json, change to eventlisteners

### PR DESCRIPTION
**Pull request by notoriousb1t**
I didn't see minification as part of the project, so this would add it
- minifies when publishing
- minifies after npm install
- minifies by calling npm run build or npm run minify

### CODE REVIEW

**Comment by fnune** [comment]
Thanks for the suggestion. I'll check it out when I have the time for it!

**Comment by notoriousb1t** [comment]
I didn't realize I was pointing to master in the pull request and a different issue was included.  If you want to evaluate it separately, I can create a new pull request against each commit

**Comment by fnune** [comment]
I'm planning to merge both branches tonight or tomorrow night when I'm done developing the new features. Maybe if you want you can wait it up and create a new pull request after that?

**Comment by notoriousb1t** [comment]
Yeah.  If you want to reply to this thread after merging in your new features, I will see if I need to make more commits to make these things work, and then let you know when it is adjusted.

**Comment by fnune** [comment]
Hi there. I've just updated spot.js to v1.1. It includes the new 3D perspective features. I won't be making another minor release in a while so maybe it's a good time to add your modifications :)

**Comment by notoriousb1t** [comment]
OK, will close this PR and reopen in new ones in a bit

**Pull request closed without merging**
