### PR TITLE
Adding a bunch of performance improvements

### PR DESCRIPTION
**Pull request by TheIronDev**
This commit adds a series of improvements, either by making the
code (slightly) smaller, or by storing function calls and lookups
as termporary variables.

I also removed the transition on the `.spot` element, since that
was making the overall look-and-feel of the shadow movement slower.

I made `showIndicators` default to falsey rather than truthy, since
it seemed more like a development-debug tool and not really something
desired with a finished product.

I changed several of the events that were `onmousemove` to
`addEventListener`, matching closer to the listeners `load`, `resize`,
and `scroll`.

I also changed the mousemove events, removing the anonymous function
wrapper (which is more costly) and replacing with the single `initiateSpot`
event function.

I also removed a bunch of unused variables.

### CODE REVIEW

**Comment by fnune** [comment]
Thank you for the effort! I'll check this out thoroughly when I get home from work. Yesterday I started a new branch on my computer and I'm actually re-designing the whole code to work like this:
1. User adds script to html file (without any options).
2. User can add effect-specific CSS classes to elements, such as spot-shadow, spot-rotate, or spot-area.

I'm thinking of a command pattern and dynamically creating objects for each element on the page that needs to be "spotted".

I think your commit will help me create the new structure too.

**Comment by fnune** [comment]
Hi again, I've just released v1.0 of my plugin. The code is completely new, in case you'd like to check it out :)

**Comment by TheIronDev** [comment]
Cool, I'm looking at the updates now. The code is  pretty different, so rebasing feels like its going to be a nightmare. I still see a couple spots in the new code base that can use some improvements, so I'm going to close this and open a new pr.

Awesome rewrite 👍

**Comment by fnune** [comment]
That sounds great, thank you! And yes, the code is pretty much new. I wanted to apply more serious design patterns.

**Pull request closed without merging**
